import type { BankEntry } from "@/data/repositories/bankRepository";
export type StatementOptions = { accounts: string[]; from: string; to: string; direction: string; method: string; category: string; project: string; summary: boolean; transactions: boolean; notes: boolean; separate: boolean };
const escape = (value: unknown) => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const money = (n:number) => `Rs ${n.toLocaleString("en-PK")}`;
const name = (key:string) => key === "personal" ? "Personal Account" : key === "builder" ? "Builder Account" : "Unassigned";
export function statementRows(entries:BankEntry[], o:StatementOptions) {
 return entries.filter(r=>o.accounts.includes(r.account_key || "unassigned") && (!o.from || r.date>=o.from) && (!o.to || r.date<=o.to) && (!o.direction || r.direction===o.direction) && (!o.method || r.method===o.method) && (!o.category || r.category===o.category) && (!o.project || r.project_id===o.project)).sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id));
}
export function buildBankStatement(entries:BankEntry[],o:StatementOptions) {
 const rows=statementRows(entries,o);
 const totals=(data:BankEntry[])=>data.reduce((t,r)=>{t[r.direction]+=r.amount;return t;},{in:0,out:0});
 function section(data:BankEntry[],title:string) {
  const t=totals(data);let net=0;
  return `<section><h2>${escape(title)}</h2><p>${data.length} transactions · ${escape(o.from || "Beginning of records")} to ${escape(o.to || "Latest record")}</p>${o.summary ? `<div class="totals"><div>Money received<strong>${money(t.in)}</strong></div><div>Money paid<strong>${money(t.out)}</strong></div><div>Net movement<strong>${money(t.in-t.out)}</strong></div></div>` : ""}${o.transactions ? `<table><thead><tr><th>Date</th><th>Person / description</th><th>Source / project</th><th>Account / method</th><th>Received</th><th>Paid</th><th>Cumulative net</th></tr></thead><tbody>${data.map(r=>{net+=r.direction==="in"?r.amount:-r.amount;return `<tr><td>${escape(r.date)}</td><td><b>${escape(r.person||r.description)}</b>${o.notes&&r.person ? `<small>${escape(r.description)}</small>` : ""}</td><td>${escape(r.category)}<small>${escape(r.project)}</small></td><td>${escape(name(r.account_key||"unassigned"))}<small>${escape(r.method)}</small></td><td class="amount">${r.direction==="in"?money(r.amount):"—"}</td><td class="amount">${r.direction==="out"?money(r.amount):"—"}</td><td class="amount">${money(net)}</td></tr>`;}).join("")}</tbody><tfoot><tr><th colspan="4">Statement totals</th><th>${money(t.in)}</th><th>${money(t.out)}</th><th>${money(t.in-t.out)}</th></tr></tfoot></table>` : ""}</section>`;
 }
 const total=totals(rows);
 return `<!doctype html><html><head><meta charset="utf-8"><title>Bank statement · Baloch Builders</title><style>@page{size:A4 landscape;margin:14mm}*{box-sizing:border-box}body{font:11px Arial,sans-serif;color:#172c3d;margin:24px}header{border-bottom:3px solid #0f766e;padding-bottom:14px}h1{font-size:25px;margin:6px 0}h2{font-size:18px;margin:18px 0 6px}p{color:#526573;line-height:1.6}.totals{display:flex;gap:14px;margin:18px 0}.totals>div{flex:1;border:1px solid #d4e1e5;padding:12px;border-radius:8px}.totals strong{display:block;margin-top:7px;font-size:17px}table{width:100%;border-collapse:collapse;font-size:10px}th{background:#eef4f5;text-align:left}td,th{padding:9px 7px;border-bottom:1px solid #dce4e8;vertical-align:middle}small{display:block;color:#617580;margin-top:4px}tr{break-inside:avoid}.amount{text-align:right;white-space:nowrap}thead{display:table-header-group}tfoot{display:table-row-group}section+section{break-before:page}footer{margin-top:18px;color:#617580;font-size:10px}@media print{body{margin:0}button{display:none}}</style></head><body><header><b>BALOCH BUILDERS & DEVELOPERS</b><h1>Bank & accounts statement</h1><p>Accounts: ${o.accounts.map(name).map(escape).join(", ")}<br>Direction: ${escape(o.direction==="in"?"Money received":o.direction==="out"?"Money paid":"Both")} · Method: ${escape(o.method||"All")} · Category: ${escape(o.category||"All")} · Project: ${escape(o.project ? entries.find(r=>r.project_id===o.project)?.project || "Selected project" : "All")}<br>Generated: ${escape(new Date().toLocaleString("en-GB",{timeZone:"Asia/Karachi"}))} (Pakistan time)</p></header><p>This statement includes all saved transactions matching these print options, across every page. Cumulative net starts at zero for this selection and is not an actual bank balance.</p>${o.separate ? o.accounts.map(key=>section(rows.filter(r=>(r.account_key||"unassigned")===key),name(key))).join("") : section(rows,"Transaction statement")}<footer><b>All selected accounts:</b> Received ${money(total.in)} · Paid ${money(total.out)} · Net movement ${money(total.in-total.out)}.<br>Prepared from saved business records. No opening bank balance is assumed.</footer></body></html>`;
}
